// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEkywsvtIcpmAiXJh7it3oWyu-coyaE1E',
    appId: '1:791074107869:web:c027d3aa6cba2f2c000634',
    messagingSenderId: '791074107869',
    projectId: 'carpark-713e9',
    authDomain: 'carpark-713e9.firebaseapp.com',
    storageBucket: 'carpark-713e9.firebasestorage.app',
    measurementId: 'G-9B7BG1DJG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCW-Q5kcmXgNMBq4pW8iH-3Q9lrGmDE20',
    appId: '1:791074107869:android:ea4d5fad01cec72b000634',
    messagingSenderId: '791074107869',
    projectId: 'carpark-713e9',
    storageBucket: 'carpark-713e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxhuCGXawzWCbuVscj4sXaMJrwHS49zvg',
    appId: '1:791074107869:ios:f974d7fce5c42853000634',
    messagingSenderId: '791074107869',
    projectId: 'carpark-713e9',
    storageBucket: 'carpark-713e9.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxhuCGXawzWCbuVscj4sXaMJrwHS49zvg',
    appId: '1:791074107869:ios:f974d7fce5c42853000634',
    messagingSenderId: '791074107869',
    projectId: 'carpark-713e9',
    storageBucket: 'carpark-713e9.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEkywsvtIcpmAiXJh7it3oWyu-coyaE1E',
    appId: '1:791074107869:web:25983f363e901e27000634',
    messagingSenderId: '791074107869',
    projectId: 'carpark-713e9',
    authDomain: 'carpark-713e9.firebaseapp.com',
    storageBucket: 'carpark-713e9.firebasestorage.app',
    measurementId: 'G-M07BLZKNRX',
  );
}
